# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:51
from __future__ import unicode_literals

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_create_follows'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CaseSensitiveUserManager()),
            ],
        ),
    ]
