# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_create_ping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ping',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='ping',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
