# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_auto_20171031_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
