# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_auto_20171101_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to=settings.AUTH_USER_MODEL),
        ),
    ]
