# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0004_auto_20171101_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='replying_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ping.Ping'),
        ),
    ]
