# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ping', '0005_add_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
