# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0006_add_mentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='ping',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='in_pings', to='ping.Hashtag'),
        ),
    ]
